server.port=8080

spring.application.name=api-gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# SITE USER SERVICE
spring.cloud.gateway.routes[0].id=blog-site-user
spring.cloud.gateway.routes[0].uri=lb://blog-site-user
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/site-user/**

# AUTH SERVICE
spring.cloud.gateway.routes[1].id=authencation-service
spring.cloud.gateway.routes[1].uri=lb://authencation-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**

# BLOG SERVICE
spring.cloud.gateway.routes[2].id=blog-service
spring.cloud.gateway.routes[2].uri=lb://blog-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/blog/**

# RAISE TICKET SERVICE
spring.cloud.gateway.routes[3].id=raise-ticker-service
spring.cloud.gateway.routes[3].uri=lb://raise-ticker-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/support/**

# MAIL SERVICE
spring.cloud.gateway.routes[4].id=email-service
spring.cloud.gateway.routes[4].uri=lb://email-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/mail/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,gateway

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


spring.cloud.gateway.httpclient.connect-timeout=5000

spring.cloud.gateway.httpclient.response-timeout=30s